### PR TITLE
can not rebuild electron 7.0.1 due to some dependences

### PR DESCRIPTION
**Pull request by Jocs**
@fxha I can not install Electron v7.0.1 due to some dependences on macOS, with errors:

```sh
In file included from ../../nan/nan.h:54:
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:129:38: error: no member named 'Value' in namespace 'v8::v8'
                inline v8::Local<v8::Value> ErrnoException(
                                 ~~~~^
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:134:29: error: incomplete type 'v8::v8::Isolate' named in nested name specifier
  return ErrnoException(v8::Isolate::GetCurrent(),
                        ~~~~^~~~~~~~~
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/ransixi/.electron-gyp/7.0.1/include/node/v8-platform.h:18:7: note: forward declaration of 'v8::v8::Isolate'
class Isolate;
      ^
In file included from ../src/keyboard-layout-manager.cc:1:
In file included from ../src/keyboard-layout-manager.h:4:
In file included from ../../nan/nan.h:54:
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:142:24: error: no template named 'Local' in namespace 'v8::v8'; did you mean simply 'Local'?
                inline v8::Local<v8::Value> UVException(int errorno,
                       ^~~~~~~~~
                       Local
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/ransixi/.electron-gyp/7.0.1/include/node/v8.h:185:7: note: 'Local' declared here
class Local {
      ^
In file included from ../src/keyboard-layout-manager.cc:1:
In file included from ../src/keyboard-layout-manager.h:4:
In file included from ../../nan/nan.h:54:
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:142:38: error: no member named 'Value' in namespace 'v8::v8'
                inline v8::Local<v8::Value> UVException(int errorno,
                                 ~~~~^
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:146:26: error: incomplete type 'v8::v8::Isolate' named in nested name specifier
  return UVException(v8::Isolate::GetCurrent(),
                     ~~~~^~~~~~~~~
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/ransixi/.electron-gyp/7.0.1/include/node/v8-platform.h:18:7: note: forward declaration of 'v8::v8::Isolate'
class Isolate;
      ^
In file included from ../src/keyboard-layout-manager.cc:1:
In file included from ../src/keyboard-layout-manager.h:4:
In file included from ../../nan/nan.h:54:
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:161:29: error: no template named 'Local' in namespace 'v8::v8'; did you mean simply 'Local'?
                NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                            ^~~~~~~~~
                            Local
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/ransixi/.electron-gyp/7.0.1/include/node/v8.h:185:7: note: 'Local' declared here
class Local {
      ^
In file included from ../src/keyboard-layout-manager.cc:1:
In file included from ../src/keyboard-layout-manager.h:4:
In file included from ../../nan/nan.h:54:
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:161:43: error: no member named 'Value' in namespace 'v8::v8'
                NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                      ~~~~^
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:163:21: error: no template named 'Local' in namespace 'v8::v8'; did you mean simply 'Local'?
                    v8::Local<v8::Object> recv,
                    ^~~~~~~~~
                    Local
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/ransixi/.electron-gyp/7.0.1/include/node/v8.h:185:7: note: 'Local' declared here
class Local {
      ^
In file included from ../src/keyboard-layout-manager.cc:1:
In file included from ../src/keyboard-layout-manager.h:4:
In file included from ../../nan/nan.h:54:
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:163:35: error: no member named 'Object' in namespace 'v8::v8'
                    v8::Local<v8::Object> recv,
                              ~~~~^
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:166:21: error: no template named 'Local' in namespace 'v8::v8'; did you mean simply 'Local'?
                    v8::Local<v8::Value>* argv));
                    ^~~~~~~~~
                    Local
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/ransixi/.electron-gyp/7.0.1/include/node/v8.h:185:7: note: 'Local' declared here
class Local {
      ^
In file included from ../src/keyboard-layout-manager.cc:1:
In file included from ../src/keyboard-layout-manager.h:4:
In file included from ../../nan/nan.h:54:
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:166:35: error: no member named 'Value' in namespace 'v8::v8'
                    v8::Local<v8::Value>* argv));
                              ~~~~^
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:168:29: error: no template named 'Local' in namespace 'v8::v8'; did you mean simply 'Local'?
                NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                            ^~~~~~~~~
                            Local
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/ransixi/.electron-gyp/7.0.1/include/node/v8.h:185:7: note: 'Local' declared here
class Local {
      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/keyboard-layout-manager/src/keyboard-layout-manager.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/ransixi/Documents/marktext/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/Users/ransixi/.nvm/versions/node/v12.11.1/bin/node" "/Users/ransixi/Documents/marktext/node_modules/electron-rebuild/node_modules/.bin/node-gyp" "rebuild" "--target=7.0.1" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-source"
gyp ERR! cwd /Users/ransixi/Documents/marktext/node_modules/keyboard-layout
gyp ERR! node -v v12.11.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@12.11.1 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   '/Users/ransixi/Documents/marktext/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ransixi/Documents/marktext/node_modules/keyboard-layout/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ransixi/Documents/marktext/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ransixi/.electron-gyp/7.0.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/ransixi/.electron-gyp/7.0.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/ransixi/Documents/marktext/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/ransixi/.electron-gyp/7.0.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/ransixi/Documents/marktext/node_modules/keyboard-layout',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/keyboard-layout-manager/src/keyboard-layout-manager.o
In file included from ../src/keyboard-layout-manager.cc:1:
In file included from ../src/keyboard-layout-manager.h:4:
In file included from ../../nan/nan.h:54:
In file included from /Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:63:
/Users/ransixi/.electron-gyp/7.0.1/include/node/v8.h:5682:1: error: unterminated /* comment
/**
^
/Users/ransixi/.electron-gyp/7.0.1/include/node/v8.h:15:2: error: unterminated conditional directive
#ifndef INCLUDE_V8_H_
 ^
In file included from ../src/keyboard-layout-manager.cc:1:
In file included from ../src/keyboard-layout-manager.h:4:
In file included from ../../nan/nan.h:54:
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:116:13: error: no template named 'Local' in namespace 'v8::v8'; did you mean simply 'Local'?
NODE_EXTERN v8::Local<v8::Value> ErrnoException(v8::Isolate* isolate,
            ^~~~~~~~~
            Local
/Users/ransixi/.electron-gyp/7.0.1/include/node/v8.h:185:7: note: 'Local' declared here
class Local {
      ^
In file included from ../src/keyboard-layout-manager.cc:1:
In file included from ../src/keyboard-layout-manager.h:4:
In file included from ../../nan/nan.h:54:
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:116:27: error: no member named 'Value' in namespace 'v8::v8'
NODE_EXTERN v8::Local<v8::Value> ErrnoException(v8::Isolate* isolate,
                      ~~~~^
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:121:13: error: no template named 'Local' in namespace 'v8::v8'; did you mean simply 'Local'?
NODE_EXTERN v8::Local<v8::Value> UVException(v8::Isolate* isolate,
            ^~~~~~~~~
            Local
/Users/ransixi/.electron-gyp/7.0.1/include/node/v8.h:185:7: note: 'Local' declared here
class Local {
      ^
In file included from ../src/keyboard-layout-manager.cc:1:
In file included from ../src/keyboard-layout-manager.h:4:
In file included from ../../nan/nan.h:54:
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:121:27: error: no member named 'Value' in namespace 'v8::v8'
NODE_EXTERN v8::Local<v8::Value> UVException(v8::Isolate* isolate,
                      ~~~~^
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:129:24: error: no template named 'Local' in namespace 'v8::v8'; did you mean simply 'Local'?
                inline v8::Local<v8::Value> ErrnoException(
                       ^~~~~~~~~
                       Local
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/ransixi/.electron-gyp/7.0.1/include/node/v8.h:185:7: note: 'Local' declared here
class Local {
      ^
In file included from ../src/keyboard-layout-manager.cc:1:
In file included from ../src/keyboard-layout-manager.h:4:
In file included from ../../nan/nan.h:54:
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:129:38: error: no member named 'Value' in namespace 'v8::v8'
                inline v8::Local<v8::Value> ErrnoException(
                                 ~~~~^
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:134:29: error: incomplete type 'v8::v8::Isolate' named in nested name specifier
  return ErrnoException(v8::Isolate::GetCurrent(),
                        ~~~~^~~~~~~~~
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/ransixi/.electron-gyp/7.0.1/include/node/v8-platform.h:18:7: note: forward declaration of 'v8::v8::Isolate'
class Isolate;
      ^
In file included from ../src/keyboard-layout-manager.cc:1:
In file included from ../src/keyboard-layout-manager.h:4:
In file included from ../../nan/nan.h:54:
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:142:24: error: no template named 'Local' in namespace 'v8::v8'; did you mean simply 'Local'?
                inline v8::Local<v8::Value> UVException(int errorno,
                       ^~~~~~~~~
                       Local
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/ransixi/.electron-gyp/7.0.1/include/node/v8.h:185:7: note: 'Local' declared here
class Local {
      ^
In file included from ../src/keyboard-layout-manager.cc:1:
In file included from ../src/keyboard-layout-manager.h:4:
In file included from ../../nan/nan.h:54:
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:142:38: error: no member named 'Value' in namespace 'v8::v8'
                inline v8::Local<v8::Value> UVException(int errorno,
                                 ~~~~^
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:146:26: error: incomplete type 'v8::v8::Isolate' named in nested name specifier
  return UVException(v8::Isolate::GetCurrent(),
                     ~~~~^~~~~~~~~
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/ransixi/.electron-gyp/7.0.1/include/node/v8-platform.h:18:7: note: forward declaration of 'v8::v8::Isolate'
class Isolate;
      ^
In file included from ../src/keyboard-layout-manager.cc:1:
In file included from ../src/keyboard-layout-manager.h:4:
In file included from ../../nan/nan.h:54:
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:161:29: error: no template named 'Local' in namespace 'v8::v8'; did you mean simply 'Local'?
                NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                            ^~~~~~~~~
                            Local
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/ransixi/.electron-gyp/7.0.1/include/node/v8.h:185:7: note: 'Local' declared here
class Local {
      ^
In file included from ../src/keyboard-layout-manager.cc:1:
In file included from ../src/keyboard-layout-manager.h:4:
In file included from ../../nan/nan.h:54:
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:161:43: error: no member named 'Value' in namespace 'v8::v8'
                NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                      ~~~~^
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:163:21: error: no template named 'Local' in namespace 'v8::v8'; did you mean simply 'Local'?
                    v8::Local<v8::Object> recv,
                    ^~~~~~~~~
                    Local
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/ransixi/.electron-gyp/7.0.1/include/node/v8.h:185:7: note: 'Local' declared here
class Local {
      ^
In file included from ../src/keyboard-layout-manager.cc:1:
In file included from ../src/keyboard-layout-manager.h:4:
In file included from ../../nan/nan.h:54:
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:163:35: error: no member named 'Object' in namespace 'v8::v8'
                    v8::Local<v8::Object> recv,
                              ~~~~^
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:166:21: error: no template named 'Local' in namespace 'v8::v8'; did you mean simply 'Local'?
                    v8::Local<v8::Value>* argv));
                    ^~~~~~~~~
                    Local
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/ransixi/.electron-gyp/7.0.1/include/node/v8.h:185:7: note: 'Local' declared here
class Local {
      ^
In file included from ../src/keyboard-layout-manager.cc:1:
In file included from ../src/keyboard-layout-manager.h:4:
In file included from ../../nan/nan.h:54:
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:166:35: error: no member named 'Value' in namespace 'v8::v8'
                    v8::Local<v8::Value>* argv));
                              ~~~~^
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:168:29: error: no template named 'Local' in namespace 'v8::v8'; did you mean simply 'Local'?
                NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                            ^~~~~~~~~
                            Local
/Users/ransixi/.electron-gyp/7.0.1/include/node/node.h:93:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^~~~~~~~~~
/Users/ransixi/.electron-gyp/7.0.1/include/node/v8.h:185:7: note: 'Local' declared here
class Local {
      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/keyboard-layout-manager/src/keyboard-layout-manager.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/ransixi/Documents/marktext/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/Users/ransixi/.nvm/versions/node/v12.11.1/bin/node" "/Users/ransixi/Documents/marktext/node_modules/electron-rebuild/node_modules/.bin/node-gyp" "rebuild" "--target=7.0.1" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-source"
gyp ERR! cwd /Users/ransixi/Documents/marktext/node_modules/keyboard-layout
gyp ERR! node -v v12.11.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (/Users/ransixi/Documents/marktext/node_modules/spawn-rx/lib/src/index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (/Users/ransixi/Documents/marktext/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.error (/Users/ransixi/Documents/marktext/node_modules/rxjs/internal/Subscriber.js:156:26)
    at Subscriber._error (/Users/ransixi/Documents/marktext/node_modules/rxjs/internal/Subscriber.js:92:26)
    at Subscriber.error (/Users/ransixi/Documents/marktext/node_modules/rxjs/internal/Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (/Users/ransixi/Documents/marktext/node_modules/rxjs/internal/Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (/Users/ransixi/Documents/marktext/node_modules/rxjs/internal/Subscriber.js:72:18)
    at SafeSubscriber._next (/Users/ransixi/Documents/marktext/node_modules/spawn-rx/lib/src/index.js:242:65)
    at SafeSubscriber.__tryOrUnsub (/Users/ransixi/Documents/marktext/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/Users/ransixi/Documents/marktext/node_modules/rxjs/internal/Subscriber.js:143:22)
```

So I degrade it to version 7.0.0, and we can upgrade it later.

---
This change is [Reviewable](https://reviewable.io/reviews/marktext/marktext/1588)

### CODE REVIEW

**Comment by Jocs** [comment]
@fxha Merge it first for development.

**Comment by fxha** [comment]
@Jocs Have do deleted `node_modules` folder because it passed CI on macOS but failed on Travis Linux worker without clearing cache. v7.0.0 is very broken and contains debug code, so we should downgrade to v6.x and remove all v7 features if there is an issue.

**Comment by Jocs** [comment]
>Have do deleted node_modules folder because it passed CI on macOS but failed on Travis Linux worker without clearing cache. v7.0.0 is very broken and contains debug code, so we should downgrade to v6.x and remove all v7 features if there is an issue.

I have install Electron 7.0.1 for many times, it seems that not compatible with macOS system, I'll try to upgrade it in this week again, we can downgrade to v6.x if it still not work...

**Comment by fxha** [comment]
> I'll try to upgrade it in this week again, we can downgrade to v6.x if it still not work...

Downgrading to v6 require to revert `nativetheme` and printing and also on Windows the jumplist is broken too.

**Comment by Jocs** [comment]
>Downgrading to v6 require to revert nativetheme and printing and also on Windows the jumplist is broken too.

I think v6.x is more stable than v7.0.1/v7.0.1, so we can release Mark Text version 0.16.0 with Electron v6.x?

**Comment by fxha** [comment]
I don't have any issue with Electron 7.0.1 on Linux and Windows and  there are some improvements. I guess v7 contains latest Node and Chromium with better performance.

**Comment by Jocs** [comment]
>I don't have any issue with Electron 7.0.1 on Linux and Windows and there are some improvements. I guess v7 contains latest Node and Chromium with better performance.

I'll try to upgrade Electron to v7.0.1 in next days. :godmode:

**Pull request merged**
