### PR TITLE
upgrade to mermaid 10

### PR DESCRIPTION
**Pull request by ivy-rew**
| Q                 | A
| ----------------- | ---
| Bug fix?          | no
| New feature?      | no
| Breaking changes? | no
| Deprecations?     | no
| New tests added?  | not needed
| Fixed tickets     | none
| License           | MIT

### Description

use latest mermaid with 'mindmap' and other new diagrams

mermaidMindmap

### CODE REVIEW

**Comment by ivy-rew** [comment]
replaces https://github.com/marktext/marktext/pull/3508

**Comment by ivy-rew** [comment]
Can you check this contribution @Jocs ? Or who is authorized to do so ? @fxha ?

**Comment by luismbendix** [comment]
Would be great to see this commit approved and added in the next update.

**Comment by ivy-rew** [comment]
> Would be great to see this commit approved and added in the next update.

@jacobwhall 's fork contains this change right now. It's already released as version 0.17.5
https://github.com/jacobwhall/marktext

feel free to consume it from there for now. But of course I'd love to see the original devs comming back and maintaining these changes in the real repo too.

**Comment by luismbendix** [comment]
Thanks for the heads up. Does that version support MacOS and Windows. The ReadMe states only linux support

**Comment by jacobwhall** [comment]
> Does that version support MacOS and Windows. The ReadMe states only linux support

@luismbendix not at the moment, please refer to [this issue](https://github.com/jacobwhall/marktext/issues/2) for more information.

**Comment by luismbendix** [comment]
I have added your @ivy-rew changes to my repo and installed the new MarkText version. Now i only get "Loading" while using a example Mermaid Mindmap.

grafik

**Review by Jocs — APPROVED** [review]

**Comment by ivy-rew** [comment]
thanks a lot @Jocs :1st_place_medal:

**Pull request merged**
