### PR TITLE
Enable macOS arm64 build target

### LINKED ISSUE #2435: Add support for macOS ARM
### Describe your feature request

Would like a universal binary able to run natively on the ARM based new M1 Macintosh computers.

### What problem does this feature solve? [optional]

Performance is the big benefit for an Apple Silicon native version.

### Additional context [optional]

Ideally build a universal binary that contains both Intel and ARM code.

### PR DESCRIPTION
**Pull request by fxha**
| Q                 | A
| ----------------- | ---
| Fixed tickets     | Closes #2435
| License           | MIT

### Description

Added an additional installer for macOS arm64 (Apple M1). This may breaks the existing update process on macOS but I'm unsure about it.

### CODE REVIEW

**Comment by Jocs** [comment]
LGTM, I have no Apple M1 macOS device, so I can not test it.

**Review by Jocs — APPROVED** [review]

**Comment by jiahao-c** [comment]
I have an M1 device and I can test it. Where can I get the built arm64 release? In the releases page, the marktext-mac.zip is only the x64 build.

**Comment by fxha** [comment]
We currently haven't any nightly builds but will provide these during testing before release. I'll /cc you.

**Comment by micdah** [comment]
I'd be more than happy to test out on M1 as well

**Comment by 3rikk** [comment]
happy to test on my m1 pro as well

**Comment by fxha** [comment]
The arm64 build for macOS can be found [here](https://github.com/marktext/marktext/releases/tag/v0.17.0-rc.1) and it would be awesome if you could give feedback. Thanks!

**Pull request merged**
