### PR TITLE
fix karma-electron nodeIntegration value due electron 5 changes

### PR DESCRIPTION
**Pull request by fxha**
| Q                | A
| ---------------- | ---
| License          | MIT

### Description

Fixed `karma-electron` nodeIntegration value due Electron 5 security changes and corrected `electron-window-state` dependency.

### CODE REVIEW

**Comment by Jocs** [comment]
AppVeyor build failed

**Comment by fxha** [comment]
I rebuild AppVeyor build but still the error but actually I just added `nodeIntegration`. Let me check this on Windows before merging.

**Comment by fxha** [comment]
I cannot reproduce the error but I added `karma-electron` to a local folder because my git on Windows failed due yarn issue. Maybe this will solve the problem as well.

**Comment by fxha** [comment]
@Jocs  OK, `karma-electron` even fails on your other PR that has neither Electron nor karma changes. It's maybe an issue with AppVeyor?

**Comment by Jocs** [comment]
>karma-electron even fails on your other PR that has neither Electron nor karma changes. It's maybe an issue with AppVeyor?

maybe due to we add some new deps after the scroll tab PR?

**Comment by fxha** [comment]
I'll remove some dependencies later and test it. The strange thing is that I cannot reproduce this issue, even a Azure Pipelines Windows instance pass all tests. My PR #953 was rebased on latest develop and it passed also. I don't know why AppVeyor fails, worst case I'll temporally disable AppVeyor tests or we move to Azure Pipelines for Windows testing.

**Pull request merged**
