### PR TITLE
Use HTTPS instead of HTTP

### PR DESCRIPTION
**Pull request by carusogabriel**
| Q                | A
| ---------------- | ---
| Bug fix?         | no
| New feature?     | no
| BC breaks?       | no
| Deprecations?    | no
| New tests added? | not needed
| Fixed tickets    | -
| License          | MIT

### Description

Safety first :shield:

### CODE REVIEW

**Comment by Jocs** [comment]
@carusogabriel there is conflicts, pls solve it first, thanks.

**Comment by Jocs** [comment]
@carusogabriel maybe you also need to update Chinese and Polish readme files.

**Comment by carusogabriel** [comment]
@Jocs Done. I've also updated it in more places :smile:

**Comment by carusogabriel** [comment]
@jocs Yes sir :+1:

**Comment by Jocs** [comment]
@carusogabriel great!

**Pull request merged**
