### PR TITLE
Opti: support 1 * 1 table

### PR DESCRIPTION
**Pull request by Jocs**
| Q                | A
| ---------------- | ---
| Bug fix?         | yes
| Fixed tickets    | #1243 
| License          | MIT

### Description

[Description of the bug or feature]

--

#### Please, don't submit `/dist` files with your PR!

---
This change is [Reviewable](https://reviewable.io/reviews/marktext/marktext/1371)

### CODE REVIEW

**Comment by Jocs** [comment]
>handleDialogTableConfirm should forbid 1x1 tables.

Do you mean we should not provide 1 * 1 table?

**Comment by fxha** [comment]
> Do you mean we should not provide 1 * 1 table?

Yes, I think so. Why do you need a 1x1 table?

**Comment by Jocs** [comment]
>Yes, I think so. Why do you need a 1x1 table?

Just obey the GFM and solve the issue.

**Comment by Jocs** [comment]
@fxha Support open 1*1 table but only support create 2*2 table

**Comment by Jocs** [comment]
>If we support 1x1 table when can also allow to create these tables.

Maybe in the future, depends on user feedback.

**Pull request merged**
