### PR TITLE
add feature: github uploader can customize branch

### PR DESCRIPTION
**Pull request by Yansongsongsong**
| Q                | A
| ---------------- | ---
| Bug fix?         | no
| New feature?     | yes
| BC breaks?       | yes
| Deprecations?    | no
| New tests added? | not needed
| Fixed tickets    | no
| License          | MIT

### Description

There is no way to customize the target branch for github uploader. so i add one new text field to check the branch.
I have manually tested it but I dont writes Unit tests for this feature.
This is my first PR in github... so if i have some mistakes in PR process, pls forgive me and tell me how to do that.
thx for your review!

--

### CODE REVIEW

**Comment by Yansongsongsong** [comment]
#1327

**Comment by Jocs** [comment]
屏幕快照 2019-09-07 下午1 10 59

I think you also need to add the default value, eg `master` in these three files.

**Comment by Yansongsongsong** [comment]
@Jocs i considered this question.
with api of _octorest_ lib if u leave branch empty, it will commit for default branch which can be one not **master** branch...
so the default value is not proper...
how do u think about it？

**Comment by Yansongsongsong** [comment]
BYW do you know why did the CI fail this time？
i have no.idea about that....:sob:

**Comment by Jocs** [comment]
>it will commit for default branch which can be one not master branch...

Yes, if the branch is empty, just delete it as you do, we can give the default value is `''`, empty string.

**Comment by Jocs** [comment]
>BYW do you know why did the CI fail this time？

I think it's due to something wrong with CI when merge PR from other repo other marktext, it's not due to this PR, so we can merge it anyway after review.

**Comment by Yansongsongsong** [comment]
@Jocs yeah, i have tried it before.
when we use empty string, the rest put failed.
in other words, if you define the branch in payload, u cant define it as empty string, or it will fail.

**Comment by Yansongsongsong** [comment]
@Jocs i dont get what u mean🤔
i have give branch one default value as `''` in view layer🤔

**Comment by Yansongsongsong** [comment]
and thank you very much for your review and explanation.:stuck_out_tongue_closed_eyes:

**Comment by Yansongsongsong** [comment]
@Jocs Oh...sorry i missed the pic you pasted before, sorry for that.. i will add it. sorry for that again....

**Comment by Yansongsongsong** [comment]
@Jocs Sorry.. I received the issue messages with one android app these days, and that app didn't display the pic you pasted ahead... so i didn't get what u mean before.
i have modify the commit and commit message. thx for your review again..

**Comment by Jocs** [comment]
@Yansongsongsong Thanks for your PR, it looks great.

**Pull request merged**
