### PR TITLE
fix: #769

### LINKED ISSUE #769: Emojis don't work properly
### Description

I discovered various issues and errors when using emojis:

- emojis are a little to big*
- emojis are not colored*
- top margin in emoji pop-up
- many exceptions when selecting an emoji using the emoji pop-up and click behind the emoji (`:hammer: <click>`)

- [x] Can you reproduce the issue? 

\*: in preview mode but when exporting everything is fine and emojis are colored.

### Steps to reproduce

mt_emojis

### Versions

- Mark Text: v0.13.65 and master
- Operating system: all

### PR DESCRIPTION
**Pull request by Jocs**
| Q                | A
| ---------------- | ---
| License          | MIT

Fix #769  #814 

Fix render error when you click the emoji picker.

### Description

[Description of the bug or feature]

--

### CODE REVIEW

**Comment by fxha** [comment]
@Jocs Your patch fixes only one case if you pick the emoji via `enter` but not if you click on the emoji.

**Comment by Jocs** [comment]
@fxha I have rewrite `setEmoji` after click or press enter, please review it.

**Comment by fxha** [comment]
@Jocs I'm fine with this but you have to remove the padding from the emoji dialog (see `diff` above).

**Comment by Jocs** [comment]
@fxha patched.

**Pull request merged**
