### PR TITLE
Add support to PlantUML diagrams

### LINKED ISSUE #603: UML diagrams using PlantUML as backend
### Describe your feature request

UML diagrams like old StackEdit (with a hack) allowed to do, using [PlantUML](https://plantuml.com) syntax and parser. It seems that UML has been asked previously in #238 and #218.

There are other things to address, but it is so this request don't fall into oblivion...

### What problem does this feature solve?

Not a problem, but a hassle :wink: . The need to add static images and edit the diagrams outside the editor. since PlantUML is an almost standalone java program (it requires Graphviz/dot for some diagrams), and very easy to install and use, it would be very nice to use it. It outputs diagrams in PNG, SVG and, for sequence diagrams, even ASCII-art :smiley:.

#### PlantUML is a component that allows to quickly write:

- Sequence diagram
- Use Case diagram
- Class diagram
- Activity diagram
- Component diagram
- State diagram
- Object diagram
- Deployment diagram  (in beta, but it's functional)
- Timing diagram (in beta, but it's functional)

#### The following non-UML diagrams are also supported:

- Wireframe graphical interface
- Archimate diagram
- Specification and Description Language (SDL)
- Ditaa diagram
- Gantt diagram (it's in beta and I still prefer Mermaid, but mermaid lacks some features for Gantt diagrams PlauntUML already has)
- Mathematic with
  - AsciiMath (which I prefer over LaTeX, see [my issue for Remarkable](https://github.com/jamiemcg/Remarkable/issues/271)) or
  - JLaTeXMath notation

They have an endpoint for online use, but, like I said, it can be downloaded and used offline, which is one of the goal of MarkText.

### Additional context [optional]

The syntaax could be a codeblock with uml type:
```
    ```uml
    [optional @startuml]
    :Here the UML code;
    [optional @enduml]
    ```
```

### PR DESCRIPTION
**Pull request by rcelha**
| Q                 | A
| ----------------- | ---
| Bug fix?          | no
| New feature?      | yes
| Breaking changes? | no
| Deprecations?     | no
| New tests added?  | not needed
| Fixed tickets     | Fixes #603
| License           | MIT

### Description

Add support to PlantUML diagrams. 

The usage is pretty much the same as for `sequence` diagrams, but with `plantuml` at the start of the code block. I went with this format for two reasons:
- It keeps compatibility with current diagrams
- It is the same format as most PlantUML plugins out there (i.e. Gitlab's)

**There are a few TODO items I need to solve, but I wanted to share an early version so I can gague if this is indeed something the project needs**

Here there are a few screenshots:

*Rendered*

render

*Source*

source

### CODE REVIEW

**Comment by Jocs** [comment]
@rcelha Can you paste the test markdown file here, so we can test this PR. thanks.

**Comment by rcelha** [comment]
> @rcelha Can you paste the test markdown file here, so we can test this PR. thanks.

Absolutely @Jocs .

You can grab a test file here: https://gist.github.com/rcelha/7bd2c6d50fd9b83b11e217dd2817036f#file-plantumltest-md

**Comment by Jocs** [comment]
@rcelha Great work, I test your example, and it runs well on my computer, I'll review this PR after you finish it.

**Comment by Jocs** [comment]
@rcelha please fix the conflicts in package.json.

**Comment by Jocs** [comment]
>There are a few TODO items I need to solve, but I wanted to share an early version so I can gague if this is indeed something the project needs

@rcelha Do you finished this PR?

**Comment by rcelha** [comment]
> > There are a few TODO items I need to solve, but I wanted to share an early version so I can gague if this is indeed something the project needs
> 
> @rcelha Do you finished this PR?

Now I have ;)

**Review by fxha — COMMENTED** [review]
Thanks for the work on this feature. I have a few questions:

1. Should it be possible to change the PlantUML render URL - especially for enterprise networks? (maybe follow-up)
2. What is the expected behavior if the user has no active internet connection?
3. Is XSS possible via the given SVG without sanitation? The input is per se untrusted.

**Comment by rcelha** [comment]
Hey @fxha, I tried to answer your questions as best as I can:

> 1. Should it be possible to change the PlantUML render URL - especially for enterprise networks? (maybe follow-up)

That would be neat. If there is demmand for this, I'd love to implement it

> 2. What is the expected behavior if the user has no active internet connection?

It will fail to render the img (the same as you'd have if you insert an html block with an `img` inside)

> 3. Is XSS possible via the given SVG without sanitation? The input is per se untrusted.

AFAIK it is not, as the  `img` element doens´t allow script execution.

From MDN:

> SVG files displayed with <image> are treated as an image: external resources aren't loaded, :visited styles aren't applied, and they cannot be interactive. To include dynamic SVG elements, try <use> with an external URL. To include SVG files and run scripts inside them, try <object> inside of <foreignObject>.

**Review by Jocs — APPROVED** [review]

**Comment by Jocs** [comment]
@fxha Do you have any more suggestions about this PR?

**Review by fxha — APPROVED** [review]
LGFM. I think we should add settings for this feature in the future, as it's a markdown extension. The user should be able to disable the feature and change the underlying URL. I'm just wondering whether we have to add a privacy-policy for this because we call a third-party URL? Are there any issue w/o this, especially with macOS app store later on?

**Comment by Jocs** [comment]
>The user should be able to disable the feature and change the underlying URL. 

I found we also has no setting(enable or disable) for `math`, `memard`, `flowchart` etc. we can add these setting later.

**Pull request merged**
