### PR TITLE
feat: front icon prepare for click menu

### PR DESCRIPTION
**Pull request by Jocs**
| Q                | A
| ---------------- | ---
| New feature?     | yes

### Description

Add icon in front of every paragraph, like `order list` , `task list`, `code block` etc. prepare for the click menu in the future.

--

### CODE REVIEW

**Comment by fxha** [comment]
Cool idea :+1: I have just one question. Why is there a gray arrow behind the icon and do you like to add a settings option to disable the icon?

mt_dot_stuff

BTW if you click on the icon, the rendering process crashes.

**Comment by Jocs** [comment]
>Cool idea 👍 I have just one question. Why is there a gray arrow behind the icon and do you like to add a settings option to disable the icon?

The little arrow to indicate that it will show a dropdown menu when you click the icon, maybe I'll delete this latter. I'm not sure.

**Comment by Jocs** [comment]
@fxha I have hidden the little arrow.

**Comment by fxha** [comment]
Still exception when clicking for example on paragraph or list icon.

**Comment by Jocs** [comment]
>Still exception when clicking for example on paragraph or list icon

Can you show me the error message or how to reproduce this, I can not reproduce this on mu computer.

**Comment by fxha** [comment]
Sometimes you have double click the icon:

mt_bug

**Comment by Jocs** [comment]
@fxha This runtime error maybe fix in #799.

**Comment by fxha** [comment]
@Jocs The issue is still present but it should be fixed in #799.

**Pull request merged**
