### PR TITLE
fix: #961

### PR DESCRIPTION
**Pull request by Jocs**
| Q                | A
| ---------------- | ---
| Bug fix?         | yes
| Fixed tickets    | #961 
| License          | MIT

### Description

[Description of the bug or feature]

--

### CODE REVIEW

**Comment by fxha** [comment]
I don't know whether this is the best way to fix this/these issue. I think we should try to figure out why there is no `BrowserWindow` defined. If not, you should add this condition to all menus and log a missing window as error. Perhaps an issue that menu is shown in the macOS menubar but not window is active?

**Comment by Jocs** [comment]
>Perhaps an issue that menu is shown in the macOS menubar but not window is active?

Yes, This error will happen when you open the dev tools and put the cursor in the `Console` tab. and click format menu item.

**Comment by fxha** [comment]
Are there more ways to trigger this issue? E.g. when all windows are closed or so?  I would say it's a won't fix if it's only reproducible via the debug window, because it's not a production issue, only an issue due incorrect use - and this would apply to all menus.

**Comment by Jocs** [comment]
>Are there more ways to trigger this issue?

I don't know, I can only reproduce this issue by the way which I described above, I think there maybe other ways to reproduce this issue.This PR may just be to fix this problem, maybe there will be a better solution later, when we have a deeper understanding of the problem.

**Comment by Jocs** [comment]
@fxha I think we can merge this PR first? and add a `TODO` above the fix codes.

**Pull request merged**
