### PR TITLE
Add support for relative image directory

### LINKED ISSUE #549: Support relative image directory
### drop  image insert by copy it to local  .${filename}.assets/  support
the current version of the marktext is upload to cloud, but in this opensource project,  upload cloud is a danger tings, the new feature of copy it to local  .${filename}.assets/  would be make a greate process

### PR DESCRIPTION
**Pull request by fxha**
| Q                 | A
| ----------------- | ---
| New feature?      | yes
| Fixed tickets     | Fixes #549
| License           | MIT

### Description

This should be the last PR before v0.16.3 release which add support for the relative image directory.

NB: You need to build Mark Text to test this PR because the development version don't load images due to some permission issues.

### CODE REVIEW

**Comment by Jocs** [comment]
@fxha great work, it works well on macOS system, only one suggestion, can we only show this area in the black box when we select `Move to designated local folder`?
Screenshot 2020-12-23 at 6 19 59 PM

**Review by Jocs — APPROVED** [review]

**Comment by fxha** [comment]
I thought about the same but the paths are also needed if the upload fails or you paste an image into MT.

**Comment by abuisman** [comment]
Thanks for this work @fxha, I was eagerly awaiting  it. Can the give. Directory also be the directory in which the markdown file is stored? As in storing an image right next to the md file.

**Comment by Jocs** [comment]
>I thought about the same but the paths are also needed if the upload fails or you paste an image into MT.

Yes, you are right, I have not thought case.

**Comment by fxha** [comment]
> Can the give. Directory also be the directory in which the markdown file is stored? As in storing an image right next to the md file.

Yes, please use `.` as relative directory name.

**Pull request merged**
