### PR TITLE
use medium-zoom to replace view-image

### PR DESCRIPTION
**Pull request by Jocs**
Use medium-zoom to zoom images with better animation.

### CODE REVIEW

**Comment by fxha** [comment]
Please fix the errors that occurred during CI testing.

**Comment by Jocs** [comment]
fixed.

**Comment by fxha** [comment]
The new library doesn't work for me because it's doesn't support a scroll and/or zoom feature, e.g. for larger images.

**Comment by Jocs** [comment]
>The new library doesn't work for me because it's doesn't support a scroll and/or zoom feature, e.g. for larger images.

It originally supported scrolling and hiding, but after using it in Mark Text, it can't be scrolled. According to his documentation, it should not support zoom. I want to know, do you think the previous good or the current is good? I can also try to add some animation to the previous `view-image` because that library is written by me.

**Comment by fxha** [comment]
I think the current used in v0.14.0 is fine and I don't care about some special effect but if you like add one later.

**Pull request closed without merging**
