### PR TITLE
Diagram

### PR DESCRIPTION
**Pull request by Jocs**
| Q                | A
| ---------------- | ---
| New feature?     | yes
| New tests added? | not needed
| Fixed tickets    | #899 
| License          | MIT

### Description

1. Diagram display in different themes.
2. export diagram only in light theme.
3. Change all icons from svg to png, to prevent from the blink of icons.

### CODE REVIEW

**Comment by Jocs** [comment]
>Scrollbar issue (image 1)

I also found this problem, but for the time being, I don’t know why. Let’s do it first. A new issue can be submitted.

**Comment by Jocs** [comment]
>Warning: The input spec uses vega-lite v3, but the current version of Vega-Lite is 3.0.0-rc12.

But we used vega-lite v3.1.0. is greater than Vega-Lite is 3.0.0-rc12?

**Comment by fxha** [comment]
BTW why we are not using `vega-embed` v4?

**Comment by Jocs** [comment]
>BTW why we are not using vega-embed v4?

It seems there are some bugs, so I used an old version.

**Comment by Jocs** [comment]
@fxha merged, can you help release the new version v0.14.0. 🎊

**Pull request merged**
