### PR TITLE
fix: #671

### PR DESCRIPTION
**Pull request by Jocs**
| Q                | A
| ---------------- | ---
| Fixed tickets    | #671 
| License          | MIT

### Description

[Description of the bug or feature]

--

### CODE REVIEW

**Comment by Jocs** [comment]
>Result: One paragraph with two spans.

`line 1` will be inserted into `header`, and `line 2` and `line 3` will combine into one paragraph.

**Comment by fxha** [comment]
Yes, that's right but this is not valid markdown/translated HTML because the generated HTML is defined as single paragraph. The produced markdown for the example above is:

```markdown
foo

# aasdline 1

line 2
line 3

foo

foo
```

**Examples per CommonMark:**

```
foo
bar

---> (translated to)

<p>foo
bar</p> <!-- only one line -->
```

```
foo<space><space>
bar

--->

<p>foo<br>
bar</p>
```

```
foo
<new line>
bar

--->

<p>foo</p>
<p>bar</p>
```

**Comment by Jocs** [comment]
I know the example what you explain, but I still didn't know what's your meaning, I think you can show me the result what you want?

**Comment by fxha** [comment]
I think the best solution would be to create two paragraphs:

```markdown
foo

# aasdline 1

line 2

line 3

foo

foo
```

**Comment by Jocs** [comment]
@fxha Why need to create two paragraphs but not one?

**Comment by fxha** [comment]
Because a single paragraph with only one new line (like `a\nb`) is defined as single line (`a b`). Either you have to add a hard line break or separate the lines as sole paragraphs.

**Comment by Jocs** [comment]
>Because a single paragraph with only one new line (like a\nb) is defined as single line (a b). 

I didn't find this Spec in GFM, can you show me this.

**Comment by fxha** [comment]
> I didn't find this Spec in GFM, can you show me this.

You can try it [here](https://spec.commonmark.org/dingus/?text=foo%0Abar%0A).

- GFM Example 182
- GFM Example 183
- GFM Example 189

**Comment by Jocs** [comment]
@fxha Maybe I need to reinterpret it because I found that I know hard line break and soft line break, but I don't understand why you need to split into two paragraphs.

the origin markdown file is:

```md
# foo<cursor>

bar

zar
```

and copyed markdown is:

```md
line 1
line 2
line 3
```

and I expect the result is:

```md
# fooline 1

line 2
line 3<cursor>

bar

zar
```

there is a soft line break after `line 1` and `line 3` before copy, and `line 1` and `line 2` and `line 3` is one paragraph with three lines. I just insert line 1 into the header `#foo`, and left the `line 2` and `line 3` to combine into one paragraph.

Is there a problem with this?

**Comment by fxha** [comment]
Now I got your point. I assumed that the pasted text is plain text. For example copy something from Wikipedia and insert into Mark Text but you assumed that the pasted text is formatted markdown, right? Can we distinguish between plain text and markdown?

**Comment by Jocs** [comment]
>Can we distinguish between plain text and markdown?

I think we have made a distinction before, there is a normal copy, copy as HTML and copy as Markdown, and then through the turndown to resolve the copy of the html, you can test whether copying the wiki article is a problem.

**Comment by fxha** [comment]
Yes, it works when pasting in an empty editor.

**Pull request merged**
