### PR TITLE
Remove underscore from dependencies

### PR DESCRIPTION
**Pull request by SukkaW**
| Q                 | A
| ----------------- | ---
| Bug fix?          | no
| New feature?      | no
| Breaking changes? | I am avoiding it
| Deprecations?     | if you consider removing underscore is kinda deprecations, yes
| New tests added?  | not needed
| Fixed tickets     | N/A
| License           | MIT

### Description

Remove `underscore` from dependencies. Use native ECMAScript instead.

### CODE REVIEW

**Comment by Jocs** [comment]
Looks GOOD to me, Can we also make a PR to https://github.com/bramp/js-sequence-diagrams? But this library hasn’t been updated for a long time.

**Comment by SukkaW** [comment]
> Looks GOOD to me, Can we also make a PR to https://github.com/bramp/js-sequence-diagrams? But this library hasn’t been updated for a long time.

Besides the project going inactive, unlike `Mark Text`, `js-sequence-diagrams` seems to be designed to work in really old browsers as well, that's why they use underscore in the first place. Without transformation tools like babel, many modern approaches (like `Array.isArray` and arrow function) would be breaking changes for them.

**Comment by Jocs** [comment]
The official sequence example seems broken on your branch.

```sh
Alice->Bob: Hello Bob, how are you?
Note right of Bob: Bob thinks
Bob-->Alice: I am good thanks!
```

**Comment by Deandeanice** [comment]
> Looks GOOD to me, Can we also make a PR to https://github.com/bramp/js-sequence-diagrams? But this library hasn’t been updated for a long time.

https://vuuzletvph.com/heads-up-vuco-bounty-programs-are-coming-your-way/

**Comment by Deandeanice** [comment]
> > Looks GOOD to me, Can we also make a PR to https://github.com/bramp/js-sequence-diagrams? But this library hasn’t been updated for a long time.
> 
> Besides the project going inactive, unlike `Mark Text`, `js-sequence-diagrams` seems to be designed to work in really old browsers as well, that's why they use underscore in the first place. Without transformation tools like babel, many modern approaches (like `Array.isArray` and arrow function) would be breaking changes for them.

https://vuuzletvph.com/heads-up-vuco-bounty-programs-are-coming-your-way/

**Comment by Jocs** [comment]
@SukkaW please solve the conflicts?

**Comment by Jocs** [comment]
@SukkaW Are you still working on this PR?

**Comment by Jocs** [comment]
I'll close this PR, feel free to reopen it if you want to continue it.

**Pull request closed without merging**
