### PR TITLE
Update build tools

### PR DESCRIPTION
**Pull request by fxha**
| Q                 | A
| ----------------- | ---
| License           | MIT

### Description

Updated all build tools:

- **Babel**: fixed wrong node.js version
- **ESLint**: updated to version 8 and fixed style issues
- **Webpack** and dependencies: updates to version 5
- misc: overall improvements

### CODE REVIEW

**Comment by fxha** [comment]
Please don't merge, there seems to be a build issue on Windows.

**Comment by Jocs** [comment]
@fxha is this PR ready for review?

**Comment by fxha** [comment]
Yes, you can review now.

**Review by Jocs — APPROVED** [review]

**Comment by Jocs** [comment]
LGTM, I have tested both development and building, and there is no problem on macOS.

**Pull request merged**
