### PR TITLE
Upgrade to N-API and Electron 11

### LINKED ISSUE #2128: Electron 9
Plan of updating Electron to version 9:

- [x] Sending non-JS objects over IPC now throws [an exception](https://www.electronjs.org/docs/breaking-changes#behavior-changed-sending-non-js-objects-over-ipc-now-throws-an-exception). We need to verify all IPC calls.
- [x] `shell.openItem` is now `shell.openPath`
- [x] Change native modules to NAPI (#1928). We could temporarily set `app.allowRendererProcessReuse` to `false` until Electron 11.

### PR DESCRIPTION
**Pull request by fxha**
| Q                 | A
| ----------------- | ---
| License           | MIT

### Description

Upgraded all native add-ons in renderer process to N-API and Electron to version 11. The minimum Node version to build Mark Text is now 12.17.

@Jocs Please test this PR in detail and also build and test the binary because there were a few issues.

Resolves #2128

---

~~Blocked by Electron v11.0.4 release due to issues with ASAR unpacking.~~

### CODE REVIEW

**Comment by fxha** [comment]
@Jocs The PR is ready to review and test, so far everything is fine on Linux and Windows.

**Comment by Jocs** [comment]
Hi @fxha it works well on macOS, only some eslint warning like bellow:

```sh
 WARNING in ./src/renderer/store/treeCtrl.js
  Module Warning (from ./node_modules/eslint-loader/dist/cjs.js):
  Cannot read property 'value' of null
  Occurred while linting /Users/ransixi/Documents/marktext/src/renderer/store/treeCtrl.js:39
   @ ./src/renderer/store/project.js 3:0-80 50:4-11 57:4-14 64:4-16 71:4-19
   @ ./src/renderer/store/index.js
   @ ./src/renderer/main.js
   @ multi ./.electron-vue/dev-client ./src/renderer/main.js
```

it maybe the issue in babel, you can refer these issues:

https://github.com/babel/babel/issues/10904
https://github.com/babel/babel-eslint/issues/681

It works well after I turn off these two eslint rules.

```js
   'template-curly-spacing': "off",
   'indent' : "off",
```

**Comment by fxha** [comment]
@Jocs Strange error, just as our CI passed... Could you check again with the patch applied?

**Review by Jocs — APPROVED** [review]

**Comment by Jocs** [comment]
done. great!

**Pull request merged**
