### PR TITLE
feat: support create indent code block

### PR DESCRIPTION
**Pull request by Jocs**
| Q                | A
| ---------------- | ---
| Fixed tickets    | #617 
| License          | MIT

### Create Indent Code block

1. input space * 4(or more) + other text.
2. Press `Shift` + `Enter`.
3. A indent code block created.

### CODE REVIEW

**Comment by Jocs** [comment]
>\´´´ is missing in indented code block:

Yes, \``` is only use for indicate it's a fence code block. just like fence code block syntax.

```md
\```languageinfo
const a = 'xxx'
\```
```

Indent code block do not use \`\`\`

**Comment by Jocs** [comment]
>a
><4 spaces + ctrl+enter>b
>c
>the code block contains a new line at the beginning

I can not understand this, why use `ctrl` + `enter`?

**Comment by fxha** [comment]
> I can not understand this, why use ctrl + enter?

Sorry `Shift+Enter`:

mt_code_block

**Comment by Jocs** [comment]
>a
><4 spaces + shift+enter>b
>c
>the code block contains a new line at the beginning

I think it's the correct behavior, because you put cursor at the beginning of `b`. Shift + Enter will create a new line before line `b`. then upgrade it to an indent code block, if you put cursor after `b`,press Shift + Enter, it also will create a new line after b.

**Pull request merged**
