### PR TITLE
Cycle through tabs

### LINKED ISSUE #1124: Tab switching shortcut please
### Steps to reproduce

1. Open multiple tabs
2. Look longingly at the tab you want and despair there is no way to reach them without touching your mouse all the way over there ---->
3. Think to yourself, this app is so beautiful and so perfect. Besides this oversight. I should put in a polite feature request.

**Expected behavior: [Ctrl]+[tab] or something would allow me to change tabs**

**Nothing I try works**

### Versions

- Mark Text:v0.14.0
- Operating system: win10

### PR DESCRIPTION
**Pull request by fxha**
| Q                | A
| ---------------- | ---
| New feature?     | yes
| Fixed tickets    | #1124
| License          | MIT

### Description

Added new shortcuts for tab management:

| Id                  | Default                                  | Description             |
| ------------------- | ---------------------------------------- | ----------------------- |
| `tabsCycle`         | <kbd>CmdOrCtrl</kbd>+<kbd>Tab</kbd>      | Cycle through tabs      |
| `tabsSwitchToLeft`  | <kbd>CmdOrCtrl</kbd>+<kbd>PageUp</kbd>   | Switch tab to the left  |
| `tabsSwitchToRight` | <kbd>CmdOrCtrl</kbd>+<kbd>PageDown</kbd> | Switch tab to the right |

---

resolves #1124

### CODE REVIEW

**Comment by yougotwill** [comment]
@fxha Just a thought but laptop keyboards don't always have PageUp and PageDown (MacBooks for example). Assuming custom keyboard shortcuts aren't being implemented for the next release, I would suggest adding one more shortcut to cycle backwards through the tabs. This behaviour is pretty standard in various browsers and apps I use.

For example:

```
tabCycleForward = 'CmdOrCtrl + Tab'
tabsCycleBackward = 'CmdOrCtrl + Shift + Tab'
```

You could use 'next' and 'previous' instead of 'forward' or 'backward'. 😄

**Comment by fxha** [comment]
Thanks @yougotwill for you feedback! I think that's a good idea to add another backward shortcut.

> Assuming custom keyboard shortcuts aren't being implemented for the next release

You can find more about key bindings [here](https://github.com/marktext/marktext/blob/develop/docs/KEYBINDINGS.md). It is available since v0.13.x or v.0.14.0.

**Comment by Nahcirn** [comment]
@fxha Not sure if this is intended behaviour or not, but these two shortcuts seem to do the same thing:


| Id | Default | Description |
| ------------- | ------------- | -------------------|
| tabsCycle | CmdOrCtrl+Tab | Cycle through tabs
| tabsSwitchToRight | CmdOrCtrl+PageDown | Switch tab to the right |

I think it would be great if "tabsSwitchToRight" actually _moved_ the tab's position. I.e. If it's currently the first tab, moving it to the right would make it the second tab.

**Comment by YanMiaoW** [comment]
@fxha @Nahcirn  move current tab left or right is important. I really need this.

**Pull request merged**
