### PR TITLE
add list indentation settings

### LINKED ISSUE #887: List indenting does not conform to CommonMark spec (breaks on BitBucket)
### Description

Mark Text adds 2 spaces to indent sub-bullets inside a list, however [the CommonMark spec](https://commonmark.org/help/tutorial/10-nestedLists.html) says it should be 4. I've also noticed that on BitBucket, sub-items with only 2 spaces of indentation are not indented but are shown on the same level.

- [x] Can you reproduce the issue? 

### Steps to reproduce

When I create a list like:

* Main bullet point
  * Sub bullet point
  * Sub bullet point

**Expected behavior:**

I would expect Mark Text to save the output file as:

```
* Main bullet point
    * Sub bullet point
    * Sub bullet point
```

**Actual behavior:**

Instead it saves it as:

```
* Main bullet point
  * Sub bullet point
  * Sub bullet point
```

And when rendered inside BitBucket, the list appears like:

* Main bullet point
* Sub bullet point
* Sub bullet point

### Versions

- Mark Text: v0.13.65 and v0.14.0-rc.1
- Operating system: Windows 10

### PR DESCRIPTION
**Pull request by fxha**
| Q                | A
| ---------------- | ---
| New feature?     | yes
| Fixed tickets    | #887
| License          | MIT

### Description

- added list indentation settings
- fixed settings update process
- update settings document text too

fixes #887

### CODE REVIEW

**Comment by Jocs** [comment]
@fxha  I pull down you branch and run locally, write markdown bellow:

```md
- foo
- bar
```

it still only one space after `-` opened by VS Code when I save as markdown file. why not be 4 space after `-`?

**Comment by fxha** [comment]
> it still only one space after - opened by VS Code when I save as markdown file. why not be 4 space after -?

It's called list indentation. Please see [here](https://github.com/marktext/marktext/blob/ead392a085047387771ee55d81fdeabf995a6841/test/unit/specs/markdown-list-indentation.spec.js#L59) for examples.

**Comment by Jocs** [comment]
Sorry, forgot to say a bit, I have set the` listIndentation` of the preference to `dfm`.

**Comment by fxha** [comment]
I don't get your point. Why should there be multiple spaces after `-` and the text? If you set `"listIndentation": "dfm"` your get something like this:

```
- asd
- asd
    - asd
        - asd
- asd
```

Right?

--- 

- `npm run dev` --> `~/.config/Electron/preference.md`
- builded application ---> `~/.config/marktext/preference.md`

**Comment by Jocs** [comment]
I maybe misunderstand the listIndentation. I consider the result be:

```md
-    asd
-    asd
     -     asd <5 spaces before `-`>
           -     asd <10 spaces before `-`>
-    asd
```
?

**Comment by fxha** [comment]
No, it just defines the indentation of sub list items/paragraphs.

**Comment by fxha** [comment]
If you want 4 spaces after the parent bullet maker, you need to set `"listIndentation": 4`:

```
- asd
     - asd <5 spaces before `-`>
           - asd <10 spaces before `-`>
- asd
```

**Pull request merged**
