### PR TITLE
refactor main source code

### PR DESCRIPTION
**Pull request by fxha**
| Q                | A
| ---------------- | ---
| License          | MIT

### Description

Please see #988. This PR need testing.

**New features:**

Allow to change user data path with `--user-data-dir <dir>` or "portable mode" if `marktext-user-data` exist in the current working directory (CWD). Portable mode doesn't work with Window Portable application because  CWD is `%temp%` by default and you don't get the original execution path.

**Further steps (further PR's):**

- [ ] EOL menu is wrong when setting it to `crlf` and loading a`lf` file. Menu seems to be set global via preferences. Can be reproduced with all versions, including v0.14.0
- [ ] Allow to add a tab without selecting it
- [ ] Make dialogs async
- [ ] Replace IPC channel prefix `AGANI::` with `mt::`
- [ ] Refactor watcher and search on disk feature/code
- [ ] Reload shortcut instance when changing keyboard layout

### CODE REVIEW

**Comment by Jocs** [comment]
@fxha Does this PR finished?

**Comment by Jocs** [comment]
@fxha In the edit menu there are endOfLine and textDirection. Do these two menu items only change the currently edited document? And will not modify the preference?

**Comment by fxha** [comment]
I removed `textDirection` from the  menu because this is a view option and should be set in settings because you either use `ltf` or `rtl`. I had moved the menu to view but to me it make no sense to keep the menu. If you like you can add it under the view menu and it's an application wide option. `endOfLine` is bugged, normally each document has a (different) `endOfLine` property and when switching tabs this value must be applied. As fallback we use the settings option. But currenlty the menu is not updated when switching tabs or loading files.

**Comment by Jocs** [comment]
> If you like you can add it under the view menu and it's an application wide option. 

I also will not use it, I think we can add it to preference setting.(All tabs will use only one `textDirection`)

**Pull request merged**
