### PR TITLE
pr template changes

### PR DESCRIPTION
**Pull request by Rexogamer**
| Q                | A
| ---------------- | ---
| Bug fix?         | somewhat
| New feature?     | no
| BC breaks?       | what does this mean
| Deprecations?    | no
| New tests added? | not needed
| Fixed tickets    | none
| License          | MIT

### Description

Using the template, the issue associated with a given pull request will now automatically close upon the PR getting merged. Also: the dist warninfpg was updated to fix a grammatical error.

#### Usage

You will now do “Fixes #[ticket number]”. For cases where multiple issues are closed, repeat the last sentence as necessary. If no tickets are fixed by the PR, put “none”.

--

### CODE REVIEW

**Comment by fxha** [comment]
@Jocs @Rexogamer First of all, thank you for your suggestion but I prefer to add the fixed issues as list to prevent a big table at the top like in the c&p template below, that is for MIT/BSD due to missing Contributor License Agreement in those licenses. Adding it to the table and to the PR title may also redundant.

```
### Description

<!-- Thank you for your contribution! Please describe the change and which issue is fixed. -->


<!--
  List of fixed issues like:
    - Fixes #<issue number>
    - Resolves #<issue number>
-->

#### Type of change

- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] A documentation update is required

### Checklist

- [ ] I've performed a self-review of my own code.
- [ ] I've tested the change on my machine that my fix/feature works.
- [ ] I've added tests, if needed.
- [ ] I've made corresponding changes to the documentation.
- [ ] I've accepted the Developer Certificate of Origin and Code of Conduct.

### Release notes

<!-- Please include a one-line description for the release notes/changelog. -->
```

**Comment by Rexogamer** [comment]
@fxha this is a PR that was merged and you’re confusing me

**Comment by fxha** [comment]
@Rexogamer  What is confusing about that? It's my opinion on the change or the older template that was not perfect because @Jocs never filled it and I always removed almost all table entries because they aren't needed, so I proposed another possibility. This would also make better changelog possible because we could query all PR's and use the *release notes* description.

**Comment by Rexogamer** [comment]
@fxha this pr is about closing the tickets upon merging the PR, I didn’t mean to make the template bigger

**Comment by fxha** [comment]
I know, you can also close a PR  via PR title like `fix: #abc XYZ`. My comment was about the general situation with the PR template that we could improve it and make it easer to fill-in.

**Comment by Rexogamer** [comment]
Ah

**Pull request merged**
