### PR TITLE
Remove unnecessary fs-extra usage

### PR DESCRIPTION
**Pull request by SukkaW**
| Q                 | A
| ----------------- | ---
| Bug fix?          | no
| New feature?      | no
| Breaking changes? | no
| Deprecations?     | no
| New tests added?  | not needed
| Fixed tickets     | N/A
| License           | MIT

### Description

`fs-extra` is great, but Node.js built-in fs API is good, too. Only use `fs-extra` when Node.js built-in fs API can't handle the problem.

### CODE REVIEW

**Comment by Jocs** [comment]
looks good, but there are still some `fs-extra` that are not replaced, can we replace them all?

**Comment by SukkaW** [comment]
> looks good, but there are still some `fs-extra` that are not replaced, can we replace them all?

That's intended. Utility function provided by `fs-extra` like `fse.copy` is much better than using native `fs` API.

**Comment by Deandeanice** [comment]
https://vuuzletvph.com/heads-up-vuco-bounty-programs-are-coming-your-way/

**Comment by Deandeanice** [comment]
https://vuuzletvph.com/heads-up-vuco-bounty-programs-are-coming-your-way/

**Comment by SukkaW** [comment]
@Jocs would you mind reporting those spam comments above?  https://github.com/marktext/marktext/pull/2690#issuecomment-984087323 & https://github.com/marktext/marktext/pull/2690#issuecomment-984087268

**Review by Jocs — APPROVED** [review]

**Comment by Jocs** [comment]
@SukkaW Thanks!

**Pull request merged**
