### PR TITLE
Disable travis windows build on linux

### PR DESCRIPTION
**Pull request by fxha**
| Q                | A
| ---------------- | ---
| Bug fix?         | yes
| License          | MIT

### CODE REVIEW

**Comment by fxha** [comment]
I'll fix this problem later. At the moment I I dont no why it's failing.

**Comment by Jocs** [comment]
@fxha OK

**Comment by fxha** [comment]
At the moment all OS's are covered by macOS and Linux builds only Linux packages.

Can you merge this?

**Comment by Jocs** [comment]
@fxha great!

**Pull request merged**
