### PR TITLE
Add symbolic link support

### PR DESCRIPTION
**Pull request by fxha**
| Q                | A
| ---------------- | ---
| New feature?     | yes
| Fixed tickets    | #784
| License          | MIT

### CODE REVIEW

**Comment by fxha** [comment]
I'll fix the symbolic links in the sidebar with the inconsistency sidebar storage because the issue already exists before and it would be necessary to rewrite some sidebar code.

**Comment by Jocs** [comment]
@fxha I have a question, is it show the `symbolic link` or `origin target pathname` on the titlebar if we open a symbolic?

**Comment by fxha** [comment]
A symbolic link is just a path to the target and the target path is shown in the titlebar but not the link path. Only hard links and real files are shown in the titlebar.

**Comment by Jocs** [comment]
>with the inconsistency sidebar storage

Do you mean the sideBar states in `store`?

**Comment by fxha** [comment]
I mean the problem that we store the markdown data in the sidebar and then load the content from the sidebar instead requesting the current file content. I'll load the markdown file from disk before opening and fix the issue with the stored markdown data in v0.15.x because it will causes problems if you load large directories.

**Comment by Jocs** [comment]
>I mean the problem that we store the markdown data in the sidebar and then load the content from the sidebar instead requesting the current file content.

I also found this problem, Let us fix it in `0.15.xx`. the side bar and main process codes need to be refactored. I'll discuss with you later after this `0.14.xx` released.

**Pull request merged**
