### PR TITLE
Ignore dist files in repository, update PRtemplate

### PR DESCRIPTION
**Pull request by alerque**
| Q                | A
| ---------------- | ---
| Bug fix?         | no
| New feature?     | no
| BC breaks?       | :shrug:
| Deprecations?    | no
| New tests added? | not needed
| Fixed tickets    | none
| License          | MIT

### Description

Fix .gitignore file to never allow dist files to be added and drop warning from PR that is cluttering up ever issue in the tracker.

### CODE REVIEW

**Comment by alerque** [comment]
Also, what the heck in "BC breaks?"?

**Comment by Jocs** [comment]
>BC breaks

Break Changes?

**Comment by Jocs** [comment]
@alerque Thanks for you PR.

**Comment by alerque** [comment]
> Break Changes?

May I suggest putting _that_ in the issue template? 'BC changes' is bad grammar and I'm not the only programmer to not even recognize what it was supposed to be.

**Comment by Jocs** [comment]
>May I suggest putting that in the issue template? 'BC changes' is bad grammar and I'm not the only programmer to not even recognize what it was supposed to be.

PR is welcomed. thanks.

**Pull request merged**
