### PR TITLE
Polish Chinese translation of README.md.

### PR DESCRIPTION
**Pull request by szzhiyang**
Polish Chinese translation of README.md.

### CODE REVIEW

**Comment by Jocs** [comment]
@szzhiyang thanks

**Comment by szzhiyang** [comment]
@Jocs 

In fact, this is the first pull request that I have ever made since I joined GitHub. 😄  Thank you for your generous contribution to improving Markdown writing experience as well as the open-source community! 👍

**Comment by Jocs** [comment]
PRs are always welcomed, and hope you make more contributions to marktext!

**Comment by szzhiyang** [comment]
@Jocs 

Surely I will! 😄 

By the way, your life experience really inspire me a lot. You are my role model! 💪

**Pull request merged**
