### PR TITLE
fix-#3019: Workaround for post window shutdown exception

### LINKED ISSUE #3019: Unexpected error: Cannot find window menu for id 1.
Hello
I am sharing this unexpected error. I hope it helps for any further development. Many thanks for your work!

### My information
mark Text v0.16.3
MacOS 12.1 (M1)

### Description

An unexpected error occurred in the main process.

I simply closed mark Text with COMMAND+Q.

### Stack Trace

```
Error: Cannot find window menu for id 1.
    at wt.getWindowMenuById (/Applications/Mark Text.app/Contents/Resources/app.asar/dist/electron/main.js:2:260308)
    at IpcMainImpl.<anonymous> (/Applications/Mark Text.app/Contents/Resources/app.asar/dist/electron/main.js:2:262431)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:157:8980)
    at Object.emit (events.js:315:20)
```

### Version

Mark Text: v0.16.3
Operating system: Darwin x64 21.2.0 (darwin)

### PR DESCRIPTION
**Pull request by fxha**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| Fixed tickets     | Fixes #3019
| License           | MIT

### Description

Add workaround for a post window shutdown exception that only occurs on macOS. Most likely due to the event loop queue.

### CODE REVIEW

**Review by Jocs — APPROVED** [review]

**Comment by Jocs** [comment]
@fxha How to use this script `deobfuscateStackTrace` ?

**Comment by fxha** [comment]
`yarn deobfuscateStackTrace -m <path_to_source_map>` where `path_to_source_map` is the `.js.map` for the stack trace you want decoded. Then paste the stack trace into the terminal and continue with 2x enter key.

**Comment by fxha** [comment]
@Jocs  Can you reproduce the linked issue and verify that is solves the exception?

**Comment by Jocs** [comment]
@fxha I can not reproduce this issue too. 😿

**Review by Jocs — APPROVED** [review]

**Pull request merged**
