### PR TITLE
update README.md

### PR DESCRIPTION
**Pull request by DIYer22**
### Description

add `<\sub>` in `README.md` and `zh_cn.md`

### CODE REVIEW

**Comment by Jocs** [comment]
@DIYer22 Any changes to Readme file when add a close `</sub>` tag?

**Comment by Jocs** [comment]
@DIYer22 Maybe need also add  close tag `</sub>` in `ja.md` and `pl.md` ?

thanks.

**Comment by Jocs** [comment]
@DIYer22 thanks for you contribution!

**Comment by DIYer22** [comment]
@Jocs  你的README 排版太好了 我打算在在你的 README.md 的基础上写自己项目的 README。我因该感谢你😄

**Pull request merged**
