### PR TITLE
support custom command as image uploader

### PR DESCRIPTION
**Pull request by thep0y**
| Q                 | A
| ----------------- | ---
| Bug fix?          | no
| New feature?      | yes
| Breaking changes? | yes
| Deprecations?     | no
| New tests added?  | not needed
| Fixed tickets     | none
| License           | MIT

### Description

Support custom command as image uploader.
`Command` receives a picture path as a parameter, and the output result is a picture link.
The `Test` button will upload the `logo.png` in the installation root directory to the specified image bed to test whether the command is available.
image

### CODE REVIEW

**Comment by DYH-Hong** [comment]
This PR fixes #2737

**Comment by fxha** [comment]
Same as in #2100. I prefer the other PR as it's resolves a few edge cases too.

**Comment by thep0y** [comment]
> Same as in #2100. I prefer the other PR as it's resolves a few edge cases too.

Apart from the null value check for `custom command`, I don't think there are other edge cases.
Users who want to use `custom command` should all be the original `typora` users, and the position of `custom command` in `typora` is entirely the responsibility of the user.
Users who wish to use `custom command` will inevitably use the `Test` button to test whether the command can be executed correctly.
I think that the handling of other edge cases is unnecessary.
This is just my subjective opinion. If you think it is incorrect, you can tell me the edge cases that you think need to be dealt with or close this pr.

**Comment by fxha** [comment]
This feature was implemented in #2100 and will be available in our next release.

**Pull request closed without merging**
