### PR TITLE
Rebase markedjs bug fixes

### PR DESCRIPTION
**Pull request by fxha**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| License           | MIT

### Description

I rebased marked.js bug fixes into our fork. The fork is now based on version 0.8.2 and includes bug fixes from v1.2.5. There was a second breaking change on version 1.0 that's not straightforward, incompatible to our changes and would require significant work to get done. I did some testing and hope I didn't break anything :smile: 

**Not included:**

- v1.0.0 (PR 1627, PR 1642, PR 1637)
- PR 1686 and follow-up PR 1755, PR 1832 - our own implementation should be fine
- PR 1664
- all list changes - we have our own implementation

### CODE REVIEW

**Comment by Jocs** [comment]
@fxha Great job, it looks good to me.

**Review by Jocs — APPROVED** [review]

**Comment by fxha** [comment]
Actually I found an issue while using this with emphasis, I'll fix it soon and notify you. BTW, could you please adapt [Muya's](https://github.com/marktext/marktext/blob/2176d241594397df345a408a9f819f01f469fbfa/src/muya/lib/parser/rules.js#L14) rules on occasion too (e.g. #2086).

**Comment by Jocs** [comment]
>could you please adapt Muya's rules on occasion too (e.g. #2086).

ok, I'll do it after you finish this PR.

**Comment by fxha** [comment]
@Jocs I reverted the em rule because markedjs use a different approach that isn't compatible with our structure.

**Review by Jocs — APPROVED** [review]

**Pull request merged**
