### PR TITLE
Fix: exception when deleting code block indentifier

### PR DESCRIPTION
**Pull request by Jocs**
| Q                | A
| ---------------- | ---
| Bug fix?         | yes
| Fixed tickets    | #1231 
| License          | MIT

### Description

[Description of the bug or feature]

--

#### Please, don't submit `/dist` files with your PR!

---
This change is [Reviewable](https://reviewable.io/reviews/marktext/marktext/1384)

### CODE REVIEW

**Comment by Jocs** [comment]
>Yes, this fixed the exception but if you switch in source-code mode after removing, the cpp still exists.

I can not reproduce this follow your steps:

remove `cpp`? and change back preview mode, the cpp is still exists?

**Comment by fxha** [comment]
@Jocs 

mt_code_block

**Comment by Jocs** [comment]
@fxha fixed can not delete code block identifier.

**Comment by fxha** [comment]
@Jocs I have sometimes problem with prism when selecting a language identifier:

```
Uncaught (in promise) TypeError: Cannot set property 'parameter' of undefined
    at Object.extend (:9091/home/felix/projects/nodejs/marktext/node_modules/prismjs/prism.js:98)
    at eval (webpack-internal:///./node_modules/prismjs/components/prism-phpdoc.js:5)
    at eval (webpack-internal:///./node_modules/prismjs/components/prism-phpdoc.js:27)
    at Object../node_modules/prismjs/components/prism-phpdoc.js (:9091/252.js:10)
    at __webpack_require__ (renderer.js:771)
    at fn (renderer.js:131)
    at Function.fn.t (renderer.js:175)
    at eval (eval at ./node_modules/prismjs/components lazy recursive ^\.\/prism\-.*$ (renderer.js:13308), <anonymous>:2974:30)
    at loadLanguages (webpack-internal:///./src/muya/lib/prism/loadLanguage.js:120)
```

**Comment by Jocs** [comment]
>I have sometimes problem with prism when selecting a language identifier:

Is it a new issue? Can you please submit a new issue for track it.

**Comment by fxha** [comment]
It's an old issue that occurs from time to time in prismjs.

**Pull request merged**
