### PR TITLE
fix #625

### LINKED ISSUE #625: Exception when selecting text in the side bar
### Description

Selecting text in the side bar leads to a renderer exception.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Open side bar and press `Ctrl+A` (select text in the side bar)
2. Set cursor in the preview mode/text area
3. Exception occurs

**Expected behavior:**

No exception.

**Actual behavior:**

Commit: a2a0363

```
index.js?d47e:479 Uncaught TypeError: Cannot read property 'id' of undefined
    at Selection.getCursorRange (index.js?d47e:479)
    at ContentState.selectionChange (paragraphCtrl.js?6d3e:20)
    at setTimeout (keyboard.js?a29c:59)
```

### Versions

- Mark Text: all
- Operating system: all

### PR DESCRIPTION
**Pull request by Jocs**
fix #625.

### CODE REVIEW

**Comment by fxha** [comment]
Just a idea: Could we check if the selection is done inside the `.editor-wrapper` part in muya's selection?

**Comment by Jocs** [comment]
@fxha pls review again.

**Comment by fxha** [comment]
@Jocs You latest changes fix the issues but create a new issue because you return `null`. You need to check if the cursor is `null` and if so don't access/change the cursor.

**Comment by Jocs** [comment]
@fxha updated

**Comment by Jocs** [comment]
This PR maybe also fix #692 ?

**Comment by fxha** [comment]
@Jocs Yet another issue:

```
index.js?51a3:90 Uncaught TypeError: Cannot read property 'key' of null
    at ContentState.set cursor [as cursor] (index.js?51a3:90)
    at HTMLDivElement.eventCenter.attachDOMEvent.event (index.js?64a7:54)
```

```js
set cursor (cursor) {
  // ...

    if (!cursor.noHistory) {
      if (
        this.prevCursor &&
        (
          this.prevCursor.start.key !== cursor.start.key || // <--- 
          this.prevCursor.end.key !== cursor.end.key        // <--- 
        )
      ) {
  // ...
  }
```

**Comment by Jocs** [comment]
>Yet another issue:

How to reproduce this error?

**Comment by fxha** [comment]
@Jocs Just raise an old cursor exception because `getCursorRange` or `findNearestParagraph` return `null`. E.g. pressing multiple times on the paragraph icon (left and right clicking). You return in both methods `null` and access the cursor later because `prevCursor` is not `null` but `start` and `end` are.

**Comment by Jocs** [comment]
@fxha updated.

**Comment by fxha** [comment]
@Jocs I found more issues:

```
Uncaught TypeError: Cannot read property 'text' of null
    at ContentState.checkNeedRender (updateCtrl.js?27d0:43)
    at ContentState.inputHandler (inputCtrl.js?0fc2:169)
    at HTMLDivElement.inputHandler (keyboard.js?a29c:136)
```

```js
ContentState.prototype.checkNeedRender = function (cursor = this.cursor) {
 // ...

    for (const token of tokenizer(startBlock.text)) { // <--- here
      if (token.type === 'text') continue
```

... and add a `null` check in all functions which use `selection.getCursorRange()`.

**Comment by Jocs** [comment]
>Uncaught TypeError: Cannot read property 'text' of null

How to reproduce this, so I can test weather I fix it?

**Comment by fxha** [comment]
This is a little difficult because it's hard to reproduce.  I pressed `Ctrl+A` and clicked on the sidebar (maybe selected text) und press `Ctrl+A` again and click on the editor.

**Comment by Jocs** [comment]
@fxha, I can not reproduce the error above, I add a `null` check to all the `selection.getCursorRange()`.

**Pull request merged**
