### PR TITLE
Opti: emoji picker style and fix missing emoji error

### LINKED ISSUE #856: Emoji name mismatch
### Description

Mark Text emoji's and GitHub's have different names.

**Related links:**

- https://gist.github.com/rxaviers/7360908
- https://gist.github.com/oliveratgithub/0bf11a9aff0d6da7b46f1490f86a71eb

### PR DESCRIPTION
**Pull request by Jocs**
- [x] Change the emoji width 42px to 36px.
- [x] fix #856 
- [x] This PR needs to wait for the electron to be upgraded to 5.0.0. it seems that that Electron@4 has bugs when render emoji with gender symbol.

**Electron@4**

屏幕快照 2019-04-29 上午12 06 06

**Electron@5**

屏幕快照 2019-04-28 下午11 39 48

### CODE REVIEW

**Comment by fxha** [comment]
I found a few issue and it seems that emojis not working correctly on Linux  (Windows not tested):

- type `:sunn:` and a horizontal scrollbar is shown
- upstream Chromium issue (on Linux?): a few emojis are not rendered and are always not colored (see image 2)
- multiple emojis per name (see image 1)

mt_emojies

mt_emojies

**Comment by Jocs** [comment]
>multiple emojis per name (see image 1)

I think maybe it's a upstream Chromium issue, because I test it on Electron v4, even more emojis are shown into two emojis, I filtered `emoij.length > 2` to avoid this issue, I update Electron to v5, and this issue seems to be fixed, I can not test it on Linux, this seems still existed on Linux? the horizontal scroll bar maybe also caused by this issue.

**Comment by Jocs** [comment]
@fxha Can you show emojis on https://missive.github.io/emoji-mart/ correctly on Linux system? (select native)

**Comment by fxha** [comment]
Yes, please see [this](https://gfycat.com/LimitedEnchantedCricket) side by side example.

But note there license:

> Image Sources
> 
> Images are extracted from their sources and this library attempts to track the latest available versions. If you're looking for older versions of Apple or Android images (such as the Hairy Heart) then you'll need to look at previous revisions.
> 
>     Apple Emoji: Copyright © Apple Inc. - macOS 10.13 (High Sierra)
>     Android Emoji: Copyright © The Android Open Source Project - 11275b5 / 2017-10-30
>     Twitter Emoji: Copyright © Twitter, Inc. - v2.3.1 2017-10-31
>     Facebook/Messenger Emoji: Copyright © Facebook, Inc. - v7, fetched 2017-11-15
> 
> Apple images are not licensed for commerical usage. Android/Google/Noto emoji are available under the Apache License 2.0. Twitter emoji are available under the Creative Commons Attribution 4.0 license. Facebook and Messenger emoji have no clear licensing.

**Comment by Jocs** [comment]
> Yes, please see this side by side example.

So, do you also it's a bug of Chromium?

**Comment by fxha** [comment]
It seems to me.

**Comment by Jocs** [comment]
>It seems to me. I think we can merge this after testing on Windows.

Ok.

**Pull request merged**
