### PR TITLE
narrow the width of edit area

### PR DESCRIPTION
**Pull request by Jocs**
As title.

### Description

[Description of the bug or feature]

--

### CODE REVIEW

**Comment by Jocs** [comment]
@fxha I just think the current edit area is too wide, maybe a user setting option is much better or different themes has different width?

**Comment by fxha** [comment]
> maybe a user setting option is much better

Do do want to open another PR/issue for this?

**Comment by Jocs** [comment]
>Do do want to open another PR/issue for this?

Not now, because no demand request yet.

**Comment by AlexanderMisel** [comment]
I was curious about this when I found the width got narrower on 0.14 release. The width is actually making me a bit uncomfortable as it uses a too small portion of screen (700/1920). The A4 layout could be achieved when users resize the window to A4 size (with the margins set).

**Comment by fxha** [comment]
@AlexanderMisel We will add an option to choose the text area width in the next release like: `small` (`550px`), `regular` (`700px`), `wide` (`800px`), `widest` (`900px`). I think we could also add `A4` with `595px`.

**Comment by andrefgneves** [comment]
Would be great if you also allowed custom values. That way people could set it to something like `75vw` to take 75% of the viewport's width or to `70ch` to have it take the width of 70 characters using the current font.

So, if the value is not one of those you proposed above, just apply the value as is. Just a thought.

**Pull request merged**
